name: Setup Environment
inputs:
  CACHIX_AUTH_TOKEN:
    required: true
    description: 'Cachix Auth Token'
  SECRET_GITHUB_TOKEN:
    required: true
    description: 'Github Secret Token'
runs:
  using: "composite"
  steps:

    - name: Installing Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        github_access_token: ${{ inputs.SECRET_GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v10
      with:
        name: tweag-jupyter
        authToken: '${{ inputs.CACHIX_AUTH_TOKEN }}'
