site_name: jupyenv
site_url: https://jupyenv.io/
repo_url: https://github.com/tweag/jupyenv
repo_name: tweag/jupyenv
edit_uri: tree/main/docs/

nav:
    - Home: index.md
    - Documentation:
      - Getting Started: documentation/getting-started.md
      - How To: documentation/how-to.md
      - Developer Guide: documentation/developers.md
      - Roadmap: documentation/roadmap.md
      - Options: documentation/options.md
    - Blog:
      - blogs/release-0.1.0.md
    - Community:
      - Get Involved: community/get-involved.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
    # lists
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    # images
    - attr_list
    - md_in_html
    # code blocks
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    # content tabs
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    # emojis
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    # admonitions/call-outs
    - admonition
    - pymdownx.details
    - pymdownx.superfences
