# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "jmp-2.0.0" = {
      name = "jmp";
      packageName = "jmp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jmp/-/jmp-2.0.0.tgz";
        sha512 = "VATfWVHErQJA2XMtmQjJQHHyQ/hxjHMmsy+egmwRk/RzFchQB4xjrR1iX496VZr+Hyhcr4zvL+IkkSlIYKx6Yw==";
      };
    };
    "jp-kernel-2.0.0" = {
      name = "jp-kernel";
      packageName = "jp-kernel";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jp-kernel/-/jp-kernel-2.0.0.tgz";
        sha512 = "Apz3AqpJhToFlo70mwnlbVyqhJRagzhNKKp84ZMeTqe/Ay9oIno8unm7eFepdlR8m8wz/9JXJQxUjK/3Ku/cpg==";
      };
    };
    "nan-2.14.2" = {
      name = "nan";
      packageName = "nan";
      version = "2.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.14.2.tgz";
        sha512 = "M2ufzIiINKCuDfBSAUr1vWQ+vuVcA9kqx8JJUsbQi6yf1uGRyb7HfpdfUr5qLXf3B/t8dPvcjhKMmlfnP47EzQ==";
      };
    };
    "nel-1.2.0" = {
      name = "nel";
      packageName = "nel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nel/-/nel-1.2.0.tgz";
        sha512 = "yt96hdYomrZC5ZvYHMCsRF5KIaZ8Aue5Gff4sH+6GmPDMJft097x5JG1DicLnfgSYE56CLP6ztZEfb+3St91Yw==";
      };
    };
    "node-gyp-build-4.2.3" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.2.3.tgz";
        sha512 = "MN6ZpzmfNCRM+3t57PTJHgHyw/h4OWnZ6mR8P5j/uZtqQr46RRuDE/P+g3n0YR/AiYXeWixZZzaip77gdICfRg==";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "zeromq-5.2.8" = {
      name = "zeromq";
      packageName = "zeromq";
      version = "5.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/zeromq/-/zeromq-5.2.8.tgz";
        sha512 = "bXzsk7KOmgLSv1tC0Ms1VXBy90+Rz27ZYf27cLuldRYbpqYpuWJfxxHFhO710t22zgWBnmdUP0m3SKFpLI0u5g==";
      };
    };
  };
  args = {
    name = "ijavascript";
    packageName = "ijavascript";
    version = "5.2.0";
    src = ./.;
    dependencies = [
      sources."jmp-2.0.0"
      sources."jp-kernel-2.0.0"
      sources."nan-2.14.2"
      sources."nel-1.2.0"
      sources."node-gyp-build-4.2.3"
      sources."uuid-3.4.0"
      sources."zeromq-5.2.8"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "IJavascript is a Javascript kernel for the Jupyter notebook";
      homepage = "https://n-riesco.github.io/ijavascript";
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
