name: Test template (daily)

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "8 0 * * *" # run on a daily basis

jobs:

  test-template:
    name: Test template
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: repo

    - name: Setup
      uses: ./repo/.github/actions/common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_TWEAG_JUPYTER_NIX_AUTH_TOKEN }}

    - name: Initialize template
      run: |
        nix flake new --template github:tweag/jupyterWith example

    - name: Build
      run: |
        cd example/
        nix build

    - name: Send message to matrix
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: 'matrix.org'
        token: ${{ secrets.MATRIX_TOKEN }}
        channel: '<!JVjIaYhrLXOiLWJfnL:matrix.org>'
        message: |
          ${{ job.status }}
